name: Python CI/CD

on:
  push:
    branches: [ cryptoHttp ]
  pull_request:
    branches: [ cryptoHttp ]
  workflow_dispatch:   # lancement manuel

jobs:
 
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
