name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Upload project files
        uses: actions/upload-artifact@v4
        with:
          name: python-project
          path: |
            *.py
            requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/download-artifact@v4
        with:
          name: python-project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pip install pytest
          pytest || echo "Aucun test trouvé, on continu..."

  dockerize:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/download-artifact@v4
        with:
          name: python-project

      - name: Build Docker image
        run: |
          echo "FROM python3" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install --upgrade pip && pip install -r requirements.txt || true" >> Dockerfile
          echo 'CMD ["python", "main.py"]' >> Dockerfile
          docker build -t python-app:latest .

      - name: Run Docker container
        run: |
          docker run --rm --name python-app-run python-app:latest

